export const websites = [
  {
    id: 1,
    type: "Event Platform",
    title: "ODDC 2025 — Detty December Carnival",
    desc: "Full-stack event management platform with attendee, vendor, sponsor, and admin portals. Paystack ticketing, real-time dashboards & SendGrid comms.",
    tags: ["Next.js", "Supabase", "Paystack"],
    emoji: "🎪",
    gradient: "linear-gradient(135deg,#BAE6FD,#38BDF8)",
    url: "https://your-project-one.com",
  },
  {
    id: 2,
    type: "E-Commerce",
    title: "Marketplace Platform",
    desc: "A multi-vendor e-commerce solution with product listings, cart management, payment integration, and a seller dashboard for inventory tracking.",
    tags: ["React", "Node.js", "MongoDB"],
    emoji: "🛒",
    gradient: "linear-gradient(135deg,#A5F3FC,#06B6D4)",
    url: "https://your-project-two.com",
  },
  {
    id: 3,
    type: "SaaS Dashboard",
    title: "Analytics Dashboard",
    desc: "Real-time data visualisation platform for business metrics. Custom charts, exportable reports, role-based access control, and API webhooks.",
    tags: ["Next.js", "Chart.js", "PostgreSQL"],
    emoji: "📊",
    gradient: "linear-gradient(135deg,#E0F2FE,#7DD3FC)",
    url: "https://your-project-three.com",
  },
  {
    id: 4,
    type: "HealthTech",
    title: "Patient Booking Portal",
    desc: "Healthcare appointment scheduling with doctor profiles, availability management, SMS reminders via Termii, and patient history tracking.",
    tags: ["Next.js", "Supabase", "Termii"],
    emoji: "🏥",
    gradient: "linear-gradient(135deg,#CFFAFE,#22D3EE)",
    url: "https://your-project-four.com",
  },
  {
    id: 5,
    type: "Blog / CMS",
    title: "Editorial Content Platform",
    desc: "Headless CMS-powered blog with markdown editor, author management, comment threads, tag taxonomy, and SEO-optimised static generation.",
    tags: ["Next.js", "Sanity", "Tailwind"],
    emoji: "✍️",
    gradient: "linear-gradient(135deg,#F0F9FF,#38BDF8)",
    url: "https://your-project-five.com",
  },
  {
    id: 6,
    type: "PropTech",
    title: "Real Estate Listings Site",
    desc: "Property listing and search platform with advanced filters, map integration, mortgage calculator, and agent lead capture via email automation.",
    tags: ["React", "Mapbox", "SendGrid"],
    emoji: "🏠",
    gradient: "linear-gradient(135deg,#BAE6FD,#0284C7)",
    url: "https://your-project-six.com",
  },
];

export const apps = [
  {
    id: 1,
    icon: "🎯",
    platform: "iOS & Android",
    name: "FocusFlow",
    desc: "Productivity & task management app with Pomodoro timer, habit tracking, and streak analytics. 4.7★ on App Store.",
    url: "#",
    downloadLabel: "Download",
  },
  {
    id: 2,
    icon: "💸",
    platform: "iOS & Android",
    name: "SplitPay NG",
    desc: "Bill splitting and expense tracking for friend groups. Naira-first with Paystack integration for instant settlement between users.",
    url: "#",
    downloadLabel: "Download",
  },
  {
    id: 3,
    icon: "🍽️",
    platform: "Android",
    name: "ChopNow",
    desc: "Local restaurant discovery and food ordering app for Nigerian cities. Real-time order tracking, vendor management, and rider dispatch.",
    url: "#",
    downloadLabel: "Get on Play Store",
  },
  {
    id: 4,
    icon: "📚",
    platform: "iOS & Android",
    name: "LearnLoop",
    desc: "Micro-learning app for developers. Daily coding challenges, bite-sized videos, quiz streaks, and peer-to-peer study rooms.",
    url: "#",
    downloadLabel: "Download",
  },
];
